spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://rktasks:3306/tasksapidb
    username: root
    password:
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://rktasks:8080/realms/tasks-api/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

applicationConfigurations:
  keycloak:
    authServerUrl: http://rktasks:8080
    realm: tasks-api
    clientId: rest-client-tasks-api
    clientSecret: kxYukJZHZyrzfyJkEwrVuGWpRNSKSRWs
  addTestData: false
  deleteTestData: false
  projectService:
    pageMaxSize: 25
  taskService:
    pageMaxSize: 25
  Default:
    pageMaxSize: 25
  FileService:
    uploadDir: C:\Users\slave\Downloads\uploads\


