spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: development

springdoc:
  api-docs:
      enabled: false
  swagger-ui:
    path: "/swagger-ui.html"
    url: "/V1/openapi.yaml"

