spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: enviroment
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  address: 0.0.0.0
  servlet:
    context-path: /tasks-api
  port: 8080

springdoc:
  api-docs:
      enabled: false
  swagger-ui:
    path: "/swagger-ui.html"
    url: "/V1/openapi.yaml"

