-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 00:33:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tasksapidb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tasksapidb` ;

-- -----------------------------------------------------
-- Schema tasksapidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasksapidb` DEFAULT CHARACTER SET utf8 ;
USE `tasksapidb` ;

-- -----------------------------------------------------
-- Table `tasksapidb`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`projects` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`projects` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(250) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `updatedAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `applicationUser` VARCHAR(250) NOT NULL COMMENT 'This column specifies the application name that used the API',
  `userName` VARCHAR(250) NOT NULL,
  `prefixIdentifier` VARCHAR(45) NOT NULL,
  `deleted` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) ,
  UNIQUE INDEX `prefixIdentifier_UNIQUE` (`prefixIdentifier` ASC) ,
  INDEX `deleted_idx` (`deleted` ASC) ,
  INDEX `createdAt_idx` (`createdAt` ASC) ,
  INDEX `updatedAt_idx` (`updatedAt` ASC) ,
  INDEX `username_idx` (`userName` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tasksapidb`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`tasks` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`tasks` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(250) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  `label` VARCHAR(250) NULL DEFAULT NULL,
  `priority` VARCHAR(250) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `applicationUser` VARCHAR(250) NOT NULL COMMENT 'This column specifies the application name that used the API',
  `dueDate` DATETIME NULL DEFAULT NULL,
  `userName` VARCHAR(250) NOT NULL,
  `projects_id` BIGINT(20) NOT NULL,
  `deleted` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`id`, `projects_id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) ,
  INDEX `fk_tasks_projects1_idx` (`projects_id` ASC) ,
  INDEX `deleted_idx` (`deleted` ASC) ,
  INDEX `status_idx` (`status` ASC) ,
  INDEX `label_idx` (`label` ASC) ,
  INDEX `priority_idx` (`priority` ASC) ,
  INDEX `createdAt_idx` (`createdAt` ASC) ,
  INDEX `due_date_idx` (`dueDate` ASC) ,
  INDEX `username_idx` (`userName` ASC) ,
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `tasksapidb`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tasksapidb`.`assigns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`assigns` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`assigns` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `identifier` CHAR(36) NOT NULL,
  `groupName` VARCHAR(250) NULL DEFAULT NULL,
  `tasks_id` BIGINT(20) NOT NULL,
  `userName` VARCHAR(250) NULL DEFAULT NULL,
  `assignDate` DATETIME NULL COMMENT 'DATETIME in UTC',
  `applicationUser` VARCHAR(250) NOT NULL,
  `deleted` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) ,
  INDEX `fk_Assigns_tasks1_idx` (`tasks_id` ASC) ,
  CONSTRAINT `fk_Assigns_tasks1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `tasksapidb`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tasksapidb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`comments` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`comments` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(250) NOT NULL,
  `tasks_id` BIGINT(20) NOT NULL,
  `identifier` CHAR(36) NOT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  `applicationUser` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `updatedAt` DATETIME NULL,
  `deleted` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) ,
  INDEX `fk_comments_users1_idx` (`userName` ASC) ,
  INDEX `fk_comments_tasks1_idx` (`tasks_id` ASC) ,
  CONSTRAINT `fk_comments_tasks1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `tasksapidb`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tasksapidb`.`spectators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`spectators` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`spectators` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(36) NOT NULL,
  `groupName` VARCHAR(250) NULL DEFAULT NULL,
  `tasks_id` BIGINT(20) NOT NULL,
  `userName` VARCHAR(250) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `applicationUser` VARCHAR(250) NOT NULL,
  `deleted` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) ,
  INDEX `fk_Assigns_tasks1_idx` (`tasks_id` ASC) ,
  INDEX `deleted_idx` (`deleted` ASC) ,
  CONSTRAINT `fk_Assigns_tasks10`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `tasksapidb`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tasksapidb`.`configurations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`configurations` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`configurations` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `configurationName` VARCHAR(250) NOT NULL,
  `configurationLabel` VARCHAR(250) NULL,
  `configurationValue` VARCHAR(250) NOT NULL,
  `description` VARCHAR(500) NULL,
  `color` VARCHAR(250) NULL COMMENT 'The UI may need to show the color of the configuration. The values that we can provide are in this format #40CB3BFF.',
  `icon` VARCHAR(250) NULL COMMENT 'The UI may need to show an icon for the configuration. The value can be a URI of the icon.',
  `createdAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `updatedAt` DATETIME NULL COMMENT 'DATETIME in UTC',
  `weight` INT NULL COMMENT 'This field is used for sorting reason',
  `applicationUser` VARCHAR(250) NULL,
  `projects_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `projects_id`),
  INDEX `fk_configurations_projects1_idx` (`projects_id` ASC) ,
  CONSTRAINT `fk_configurations_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `tasksapidb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasksapidb`.`attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`attachments` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`attachments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(45) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `mimeType` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  `applicationUser` VARCHAR(250) NOT NULL,
  `userName` VARCHAR(250) NOT NULL,
  `uploadedAt` DATETIME NULL,
  `deleted` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasksapidb`.`comments_has_attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasksapidb`.`comments_has_attachments` ;

CREATE TABLE IF NOT EXISTS `tasksapidb`.`comments_has_attachments` (
  `comments_id` BIGINT(20) NOT NULL,
  `attachments_id` BIGINT NOT NULL,
  PRIMARY KEY (`comments_id`, `attachments_id`),
  INDEX `fk_comments_has_attachments_attachments1_idx` (`attachments_id` ASC) ,
  INDEX `fk_comments_has_attachments_comments1_idx` (`comments_id` ASC) ,
  CONSTRAINT `fk_comments_has_attachments_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `tasksapidb`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_has_attachments_attachments1`
    FOREIGN KEY (`attachments_id`)
    REFERENCES `tasksapidb`.`attachments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
