openapi: 3.0.0

info:
  version: 1.0.0
  title: Task API
  description: The purpose of this API is for external systems to manage tasks

servers:
  - url: http://localhost:8080
    description: Task API location

tags:
  - name: Tasks

paths:
  /tasks:
    get:
      description: Returns all tasks from the system that the user has access to
      tags:
        - "Tasks"
      operationId: getTasks
      responses:
        "200":
          description: A list of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{identifier}/comments:
    get:
      description: Returns all the comments from the task with a specific identifier
      tags:
        - "Tasks"
      operationId: getTaskComments
      parameters:
        - name: identifier
          in: path
          description: identifier of the task
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'


components:
  schemas:
    Task:
      description: This is a task object
      type: object
      required:
        - name
        - status
      properties:
        identifier:
          description: |
            This is the unique identifier of the task and the system returns this value in the get request.
            This value is going to be produced by the system in the post request.
            If someone specifies this value in the post request the system is going to ignore this field.
          type: string
          format: uuid
        name:
          description: This is the name of the task
          type: string
        description:
          description: This is the description of the task
          type: string
        status:
          description: This is the current status of the task
          type: string
        dueDate:
          type: string
          pattern: '^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$'
          description: Creation date and time
          example: "2021-01-30T08:30:00Z"
    Comment:
      description: This is a comment object that belongs to a Task
      type: object
      required:
        - text
      properties:
        identifier:
          description: |
            This is the unique identifier of the comment and the system returns this value in the get request.
            This value is going to be produced by the system in the post request.
            If someone specifies this value in the post request the system is going to ignore this field.
            type: string
            format: uuid
        text:
          description: This is the text of the comment
          type: string
        creationDate:
          type: string
          pattern: '^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$'
          description: Creation date and time
          example: "2021-01-30T08:30:00Z"